apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: eq-sd-worflow-template
  namespace: argo
spec:
  entrypoint: load-data
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  arguments:
    parameters:
      - name: output_date
        value: "20250125"
  templates:
    - name: load-data
      dag:
        tasks:
        - name: data-downloader
          template: data-downloader-template
        - name: consumer
          dependencies: [ data-downloader ]
          template: consumer-template
        - name: mapper
          dependencies: [ consumer ]
          template: mapper-template
        - name: data-uploader
          template: data-uploader-template
          dependencies: [ mapper ]

    - name: data-downloader-template
      container:
        image: com.jk/object-storage-loader
        imagePullPolicy: Never
        command: [ "java","-Dspring.profiles.active=download", "-Dspring.config.location=file:/spring/config/application.yaml", "-jar","/app.jar" ]
        volumeMounts:
          - mountPath: /work
            name: data-volume
          - name: config-volume
            mountPath: /spring/config
      volumes:
        - name: config-volume
          configMap:
            name: eq-sd-loader-config
    - name: consumer-template
      container:
        image: com.jk/spark-mapper
        imagePullPolicy: Never
        env:
          - name: JDK_JAVA_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: java-opts
                key: java_opts
          - name: OUTPUT_DATE
            value: "{{ workflow.parameters.output_date }}"
        command: [ "java", "-Dspring.config.location=file:/spring/config/application.yaml", "-jar","/app.jar" ]
        volumeMounts:
          - name: config-volume
            mountPath: /spring/config
          - mountPath: /work
            name: data-volume
      volumes:
        - name: config-volume
          configMap:
            name: eq-sd-consumer-config
    - name: mapper-template
      container:
        image: com.jk/spark-mapper
        imagePullPolicy: Never
        env:
          - name: JDK_JAVA_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: java-opts
                key: java_opts
          - name: OUTPUT_DATE
            value: "{{ workflow.parameters.output_date }}"
        command: [ "java", "-Dspring.config.location=file:/spring/config/application.yaml", "-jar","/app.jar" ]
        volumeMounts:
          - name: config-volume
            mountPath: /spring/config
          - mountPath: /work
            name: data-volume
      volumes:
        - name: config-volume
          configMap:
            name: eq-sd-mapper-config
    - name: data-uploader-template
      container:
        image: com.jk/object-storage-loader
        imagePullPolicy: Never
        command: [ "java","-Dspring.profiles.active=upload", "-Dspring.config.location=file:/spring/config/application.yaml", "-jar","/app.jar" ]
        volumeMounts:
          - mountPath: /work
            name: data-volume
          - name: config-volume
            mountPath: /spring/config
      volumes:
        - name: config-volume
          configMap:
            name: eq-sd-loader-config